### ISSUE TITLE
Incorrect behaviour when a string is joined with one of its own letters

### ISSUE THREAD

**Issue by yaxollum** [scraterpreter/scrape#2]
Scratch program (with .sb3 file and .scrape file) attached here: [test_files.zip](https://github.com/scraterpreter/scrape/files/4711878/test_files.zip).

![Screenshot from 2020-06-01 10-45-00](https://user-images.githubusercontent.com/46109467/83420687-f8382c00-a3f4-11ea-948e-c71b8c1dced1.png)

When run on MIT Scratch, the output is:
```
scrape
scrapea
```
When run using Scrape, the output is:
```
scrape
scrapeape
```
As you can see, Scrape adds two extra letters ("pe") to the second line of output.

**Comment by hillcrestpaul0719** [comment]
fixed in 20.06.1 release
